from __future__ import annotations

from framework import SeleniumBasePage


class ExamplePage(SeleniumBasePage):
    """Sample page object generated by the scaffolding tool."""

    def __init__(self, base_factory: SeleniumBasePage, base_url: str | None = None) -> None:
        super().__init__(base_factory.driver)
        resolved = base_url or "{{BASE_URL}}"
        self.base_url = resolved.rstrip("/")

    def visit(self) -> None:
        self.driver.get(self.base_url)
